In [1]:
import torch
import torch.nn as nn

# RNN

In [7]:
input_size = 10
hidden_size = 20
batch_size = 2
torch.manual_seed(21)
rnn = nn.RNN(10, 20 ,2, batch_first=True)
rnn

RNN(10, 20, num_layers=2, batch_first=True)

In [52]:
input = torch.randn(1, 3, 10)
input

tensor([[[-0.0857, -0.1165, -0.7614, -0.1124, -0.6543, -0.9479,  0.0521,
          -0.1138, -1.1834,  0.5078],
         [-0.8968, -0.7224, -0.3704, -0.5789,  1.5855,  0.3386, -0.2433,
          -0.8137,  0.4939,  0.7648],
         [-0.3690,  1.7444,  0.8344,  0.5330, -0.0036, -0.8654, -1.0176,
           0.7904, -0.5131,  1.4615]]])

In [28]:
h0 = torch.randn(2, 1, 20)
h0

tensor([[[ 0.5372, -0.5294, -0.3277, -0.3887, -0.9055, -1.4915,  1.2034,
           1.9048, -1.3002, -0.4156, -0.8998, -0.0748, -1.4028,  0.9531,
          -0.0035,  0.4503, -0.8434, -0.2161,  0.3604, -0.2755]],

        [[ 0.3582,  0.1813,  1.0000,  0.1013, -0.2593,  0.3105,  0.8330,
          -0.7441, -2.2806,  0.2765,  0.3489, -1.3150, -0.2325,  0.6551,
           0.8673,  0.1192, -2.7486, -0.8374,  0.8782,  0.3478]]])

In [29]:
out, h_n = rnn(input, h0)

In [30]:
out

tensor([[[-0.4396, -0.6562,  0.8638, -0.5782, -0.3710,  0.4650,  0.6931,
           0.1513,  0.3309, -0.0937, -0.2632,  0.0593,  0.5907,  0.2825,
           0.6017, -0.4075,  0.4190,  0.4201,  0.1884, -0.6215],
         [-0.0572,  0.4153,  0.2256,  0.0695, -0.6654,  0.4567,  0.0729,
           0.2637, -0.4042,  0.1540, -0.2481,  0.2365, -0.5188, -0.1155,
          -0.1334, -0.0671, -0.2713,  0.1464,  0.4435, -0.3995],
         [-0.4226, -0.4999,  0.0227, -0.3280, -0.0496,  0.2048,  0.3474,
          -0.2681,  0.3245,  0.1677,  0.0728,  0.4872,  0.0081, -0.2121,
           0.4044,  0.0924,  0.0380, -0.0560, -0.0275, -0.0791]]],
       grad_fn=<TransposeBackward1>)

In [31]:
h_n

tensor([[[ 0.3617, -0.5248,  0.9209, -0.2786,  0.5032,  0.6951,  0.1788,
          -0.4632, -0.0581, -0.4583,  0.0506, -0.2557, -0.6842,  0.3077,
          -0.0571,  0.2813, -0.1048,  0.3407,  0.2768, -0.8417]],

        [[-0.4226, -0.4999,  0.0227, -0.3280, -0.0496,  0.2048,  0.3474,
          -0.2681,  0.3245,  0.1677,  0.0728,  0.4872,  0.0081, -0.2121,
           0.4044,  0.0924,  0.0380, -0.0560, -0.0275, -0.0791]]],
       grad_fn=<StackBackward0>)

# RNNCell

In [11]:
input_size = 10
hidden_size = 20
batch_size = 2
torch.manual_seed(21)
rnn_cell = nn.RNNCell(input_size, hidden_size)

In [12]:
input_cell = torch.randn(batch_size, input_size)
input_cell

tensor([[-0.8824,  0.4475, -0.0697,  0.4843,  0.0603, -0.0267,  0.6202, -0.0993,
         -0.7855, -0.5672],
        [ 0.6444,  1.1828,  0.3015,  0.4238,  1.0613, -2.0163, -2.0719,  0.5075,
          0.6785, -0.9038]])

In [13]:
hc0 = torch.randn(batch_size, hidden_size)
hc0

tensor([[ 0.0650, -0.2198, -0.1083,  2.3743,  0.3493, -0.5043,  0.8396,  0.1794,
         -2.4422, -0.7257, -0.7872, -1.3241,  0.4547, -1.2128, -1.0707, -0.0697,
          1.1988,  0.2343,  1.3104,  0.4559],
        [-0.3838,  2.2650,  0.7828,  0.0151, -0.5575,  0.7666, -0.4113,  0.5744,
          1.2408,  0.2365,  0.6974,  0.1379, -1.4334,  1.1186,  0.8338, -0.2819,
         -0.3629, -0.0197, -1.1684, -0.4149]])

In [14]:
out = rnn_cell(input_cell, hc0)

In [15]:
out

tensor([[-0.7859, -0.4846, -0.3767,  0.1959, -0.5258, -0.3927,  0.0777,  0.9355,
          0.7413,  0.4142, -0.4805,  0.0461, -0.4823, -0.7204, -0.6232,  0.0096,
         -0.1987,  0.0595, -0.8654, -0.3242],
        [ 0.0719,  0.3221, -0.8402,  0.0806,  0.2154, -0.0429, -0.6667,  0.7800,
         -0.4567, -0.7715, -0.7125, -0.0038,  0.8092,  0.4360,  0.5240, -0.2719,
         -0.7112,  0.1005,  0.9650,  0.7769]], grad_fn=<TanhBackward0>)

In [23]:
input = torch.randn(6, 3, 10) #每一个batch代表一个序列在时间t的token
input

tensor([[[-1.0138e+00, -2.2926e+00, -3.0382e-01,  1.4221e+00,  1.0336e-03,
           2.6167e+00, -1.3699e-02,  4.5220e-01,  7.7482e-02, -1.4080e+00],
         [ 1.5163e-01, -1.1997e+00,  1.4642e+00, -1.4127e+00, -1.8213e-01,
           2.2480e+00,  2.6321e-01,  2.7694e-01,  9.4766e-02, -7.3950e-01],
         [-6.8964e-01, -4.5755e-01, -1.0317e+00, -4.4529e-01,  8.9270e-03,
           1.7767e-01, -5.8809e-01,  1.7665e+00, -4.4935e-01, -4.9249e-02]],

        [[-3.3310e-01, -8.5486e-01,  1.3211e-01,  5.8833e-01,  2.8587e-01,
          -3.2967e-01, -5.1813e-01,  3.6815e-02, -2.0288e-01, -3.8437e-01],
         [-4.4735e-01, -1.7346e+00,  1.0968e+00,  8.4306e-01, -3.8690e-01,
           9.3929e-01, -5.0257e-01, -4.7191e-01,  1.2474e+00, -6.8161e-01],
         [-1.4703e+00,  1.8625e+00, -5.1893e-01, -7.4265e-01,  5.8878e-01,
          -1.9954e-01, -3.1837e-01, -1.0135e+00,  4.8666e-01,  3.2934e-01]],

        [[-6.4650e-01,  1.0858e-01,  1.1042e-02, -3.0831e-02, -2.1035e-02,
           7.49

In [17]:
input[0]

tensor([[-1.7059,  0.0680, -0.2176, -0.1429, -0.4851, -0.4177,  0.3259,  0.8947,
          0.0133, -0.6168],
        [-1.5213,  0.6643,  1.4960, -1.1990, -0.6115, -0.1654,  0.4335,  0.7979,
          1.6696,  0.0105],
        [ 0.6249, -0.2422,  0.9145,  0.4950,  1.7437, -0.5851,  0.9369, -1.0811,
          0.9017, -2.5059]])

In [18]:
hx = torch.randn(3, 20)
hx

tensor([[-8.0690e-01, -5.3114e-01,  3.8099e-01,  1.0328e+00, -3.6761e-01,
         -1.5094e+00,  8.7217e-01, -1.3194e+00, -1.3328e+00, -9.7695e-01,
         -1.6199e-01, -1.8421e+00, -7.3778e-02, -1.2432e+00,  4.3033e-01,
          1.6238e+00,  9.1694e-01, -3.3583e-01,  6.0912e-01,  9.9074e-01],
        [ 1.3391e+00,  9.2119e-02, -1.3209e+00,  3.7271e-01, -6.8408e-01,
          5.6864e-01,  1.0816e-01, -9.8363e-01, -3.1234e-01,  1.5988e+00,
         -2.7983e+00, -1.3241e-01,  7.6513e-01,  9.3578e-01,  8.6657e-04,
         -1.2838e+00,  2.3537e-01,  1.1354e+00,  1.4175e+00, -2.2500e-01],
        [ 9.8291e-01,  6.4172e-01,  4.5572e-02, -1.3810e-01, -1.5340e+00,
          2.9626e-01,  2.4972e-01, -1.4058e-01, -5.1218e-01, -6.9259e-01,
          6.0946e-01,  3.0293e-01,  4.1070e-01,  9.5792e-01, -3.3112e-01,
          1.0344e+00, -1.7883e+00,  1.0993e+00,  2.4072e-01, -1.1576e-01]])

In [20]:
output = []
for i in range(6):
    hx = rnn_cell(input[i], hx)
    output.append(hx)

In [25]:
output #最后一个是三个序列的final hidden state

[tensor([[-0.6549, -0.8316, -0.7075,  0.8273,  0.2440, -0.6770, -0.4075,  0.8631,
           0.9611,  0.4345, -0.3207, -0.5118, -0.3118, -0.1427,  0.0527, -0.5221,
          -0.2657,  0.1050, -0.6316, -0.1892],
         [ 0.1589, -0.7557,  0.3029, -0.9028,  0.1547,  0.0293,  0.3999, -0.1306,
           0.5554, -0.8160, -0.9199, -0.1551, -0.9515, -0.5880,  0.2167, -0.1946,
          -0.5477, -0.4530, -0.2684, -0.9890],
         [-0.3297,  0.8431, -0.1819, -0.7646, -0.3079,  0.7712,  0.1233, -0.2972,
          -0.0513,  0.4720, -0.5362, -0.6491, -0.2978, -0.1986,  0.5728,  0.6194,
          -0.3006,  0.6240,  0.8284, -0.8839]], grad_fn=<TanhBackward0>),
 tensor([[ 0.0441, -0.6906,  0.2436,  0.2554,  0.2033,  0.0363, -0.3208, -0.0716,
          -0.4348, -0.3089, -0.1094, -0.3683,  0.2446,  0.1089, -0.3885, -0.5192,
          -0.5485, -0.3516, -0.3782,  0.8994],
         [ 0.3298,  0.3464,  0.3758,  0.0308, -0.1063,  0.7729, -0.5925, -0.7490,
          -0.1530,  0.2304,  0.2145, -0.7544,  